POST http://localhost:5000/users
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Userenko",
  "isMale": true,
  "email": "userUsserae1nko@example4279.com",
  "password": "supersecurepassword123",
  "passwordRepeat": "supersecurepassword123"
}