const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  CHANGE_THEME: 'CHANGE_THEME',
};

export default ACTION_TYPES;
