POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTczOTU1MjcxNywiZXhwIjoxNzQwMTU3NTE3fQ.yw1FCLWdvDXvRgGJp5E5r1ApqdRROo7FlBnQnbpdHMI"
}